version: '3.9'

services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: delivery-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: delivery-app
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - delivery-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: delivery-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - delivery-network

  # Mailhog (для тестирования email в разработке)
  mailhog:
    image: mailhog/mailhog
    container_name: delivery-mailhog
    restart: unless-stopped
    ports:
      - '1025:1025' # SMTP server
      - '8025:8025' # Web UI
    networks:
      - delivery-network

  # MinIO (S3-совместимое хранилище для разработки)
  minio:
    image: minio/minio
    container_name: delivery-minio
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - delivery-network

networks:
  delivery-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  minio_data:
